### ISSUE TITLE
report errors

### ISSUE THREAD

**Issue by Kaery40** [CodedSakura/FabricHomes#5] opened 2021-04-22 07:24 UTC
[15:02:54] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/entity/EntityComponentInitializer
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at eu.codedsakura.fabrichomes.FabricHomes.homeSet(FabricHomes.java:149) ~[FabricHomes-0.1.3.jar:?]
        at eu.codedsakura.fabrichomes.FabricHomes.lambda$null$2(FabricHomes.java:76) ~[FabricHomes-0.1.3.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[intermediary-server.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:249) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:342) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:315) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:814) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zfn000$modifiedRunLoop(MinecraftServer.java:4320) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:260) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.entity.EntityComponentInitializer
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
        ... 17 more

**Comment by CodedSakura** [comment] 2021-04-22 07:37
Can you provide more info on MC version, FabricAPI version, FacricHomes version and whether you're using FabricWarps, FabricTPA or other of my mods?

**Comment by Kaery40** [comment] 2021-04-22 07:42
fabric-api-0.32.9
FabricHomes-0.1.3
FabricTPA-2.0.1
FabricWraps-0.2.1

**Comment by CodedSakura** [comment] 2021-04-22 07:55
Hmm, i can't manage to reproduce this, what are the steps you took for this to happen?

**Comment by Kaery40** [comment] 2021-04-22 07:59
What solutions are there? tps homes warps It's all up to date. Releases

**Comment by CodedSakura** [comment] 2021-04-22 08:01
yea, i'm trying to understand what caused this, as i cannot get this error using the mod versions you provided.
what causes this error to happen to you?

**Comment by Kaery40** [comment] 2021-04-22 08:12
simpleauth-1.7.7
tabtps-fabric-mc1.16.5-1.3.5
fabric-carpet-1.4.32

**Comment by CodedSakura** [comment] 2021-04-22 08:46
i assume this is also on 1.17? (based on CodedSakura/FabricTPA#18)

**Comment by Kaery40** [comment] 2021-04-22 08:48
yes！

**Comment by CodedSakura** [comment] 2021-04-22 08:49
then this is a duplicate of #3

**Closed as completed by CodedSakura** 2021-04-22 08:49 UTC
Labels: bug, duplicate
